### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by fabiosussetto** [AlexanderPoellmann/PaymentFont#103]
Hi, I noticed you have a package.json file but the project doesn't seem to be published on npm. That would be quite useful!

**Comment by SimeonC** [comment]
I agree! I'd be happy to help set this up and transfer ownership if needed as I've done it on other projects.

**Comment by avimar** [comment]
NPM is complaining about 2 JSON issues, which are addressed by https://github.com/vendocrat/PaymentFont/pull/117

**Comment by AlexanderPoellmann** [comment]
Should be fixed in v1.2.0!
