### ISSUE TITLE
Request: New Mastercard/Maestro/Cirrus logo

### ISSUE THREAD

**Issue by LKay** [AlexanderPoellmann/PaymentFont#129]
From the beginning of October 2016 Mastercard cards family is officially using new logos. It would be nice to update the existing ones and preserve the old ones.

Here is the reference:
- https://brand.mastercard.com/brandcenter/mastercard-brand-mark/downloads.html
- https://brand.mastercard.com/brandcenter/other-marks.html

**Comment by AlexanderPoellmann** [comment]
Updated in v1.2.0 👍
