### ISSUE TITLE
Update: amazon pay Logo

### ISSUE THREAD

**Issue by japadi83** [AlexanderPoellmann/PaymentFont#144]
New Logo for amazon pay:

![button_gold_m _v526162779_](https://cloud.githubusercontent.com/assets/20238005/23750574/e480fd6e-04cd-11e7-94f0-02afe5397d17.png)

https://pay.amazon.com/de/merchant/tools

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
