### ISSUE TITLE
Icon request: Venmo

### ISSUE THREAD

**Issue by mstueve** [AlexanderPoellmann/PaymentFont#38]
Would it be possible to add a Venmo icon? Thanks!

**Comment by AlexanderPoellmann** [comment]
Hi, can you provide a logo image so that I get the right one?

**Comment by mstueve** [comment]
Hi, Venmo offers brand assets available for download here:
http://brand.venmo.com/styleguide

Thanks!

**Comment by cassidoo** [comment]
I see that this has been closed, but it's not on the website/in the README.  When will it be available?

**Comment by xd1936** [comment]
+1

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
