### ISSUE TITLE
[Icon Request] Visa Debit

### ISSUE THREAD

**Issue by leandroiwai** [AlexanderPoellmann/PaymentFont#43]
Hi, this font selection is quite handy. I just have one request, Visa Debit, which would be Electron but here in Ireland we call it Visa Debit instead. The font used on the electron and debit is the same.

http://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Visa_Debit_SVG_logo.svg/1280px-Visa_Debit_SVG_logo.svg.png

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
