### ISSUE TITLE
Klarna (klarna.com)

### ISSUE THREAD

**Issue by kvakvs** [AlexanderPoellmann/PaymentFont#45]
A large payment and online micro-loans provider in Nordic countries (Sweden, Norway, Finland, Denmark), DACH (Germany, Austria, Switzerland), and Netherlands, building presence in UK and USA.

https://klarna.com/

Klarna Logo in SVG is googlable, or can probably be requested from Klarna itself.

**Comment by calumbrodie** [comment]
https://www.klarna.com/application/files/5214/2739/0062/Klarna_footer.svg

This is the .svg in use on the Klarna website.

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
