### ISSUE TITLE
Interac icon is incorrect

### ISSUE THREAD

**Issue by xorgy** [AlexanderPoellmann/PaymentFont#51]
Interac's logo has changed a bit, also it should probably be negative rather than positive by default.

This is what the new logo looks like.
Negative:
![interac_negative](https://cloud.githubusercontent.com/assets/1272018/7326021/c4c514fc-eab1-11e4-9c8b-69a4f4a4a0aa.png)
Positive:
![interac_positive](https://cloud.githubusercontent.com/assets/1272018/7326035/e51cad64-eab1-11e4-8824-0a5f6ac2db01.png)

Here are the SVGs for these.
[interac negative logo (should be default)](http://marumie.magnifi.ca:8080/ipfs/QmRrSJWCttfyp8asaJ1ekExAmDZDbcofjsyKy9cpitcGSU/interac_negative.svg)
[(alternate host) interac negative logo (should be default)](https://ipfs.io/ipfs/QmRrSJWCttfyp8asaJ1ekExAmDZDbcofjsyKy9cpitcGSU/interac_negative.svg)
[interac positive logo (should be alt)](http://marumie.magnifi.ca:8080/ipfs/QmRrSJWCttfyp8asaJ1ekExAmDZDbcofjsyKy9cpitcGSU/interac_positive.svg)
[(alternate host) interac positive logo (should be alt)](https://ipfs.io/ipfs/QmRrSJWCttfyp8asaJ1ekExAmDZDbcofjsyKy9cpitcGSU/interac_positive.svg)

**Comment by AlexanderPoellmann** [comment]
Thanks for the heads up, will be changed in the upcoming release!

**Comment by AlexanderPoellmann** [comment]
Update in v1.2.0 👍
