### ISSUE TITLE
Icon request: Alipay icon

### ISSUE THREAD

**Issue by gabrielsantos** [AlexanderPoellmann/PaymentFont#66]
Alipay: http://global.alipay.com/ospay/home.htm

**Comment by edelprino** [comment]
:+1:

**Comment by ryh** [comment]
This one https://t.alipayobjects.com/images/T11rdgXbFkXXXXXXXX.png (from https://www.alipay.com) is more official,
the one on global  page is not public and widely used, And they did not update http://global.alipay.com for years(Check the `About Us` Page)

**Comment by ryh** [comment]
let us bring in Alipay guy @lifesinger

**Comment by freeyoung** [comment]
+1

**Comment by firstred** [comment]
:+1:

**Comment by pienisieni** [comment]
Need this!

Alipay covers half of the Chinese online payment market.. it's pretty big you know..

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
