### ISSUE TITLE
Sodexo payment icon

### ISSUE THREAD

**Issue by mheigl** [AlexanderPoellmann/PaymentFont#87]
Hi!

Great icon font - thank you very much! Maybe you could add Sodexo - they are issueing vouchers that are accepted by many shops around the world: http://giftpass.sodexomerchant.com/

![sodexo](https://cloud.githubusercontent.com/assets/1484628/8957930/1406c2a4-3602-11e5-8f7f-f66b19d45710.jpg)

Cheers,
Michael

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
