### ISSUE TITLE
direct debit

### ISSUE THREAD

**Issue by maznu** [AlexanderPoellmann/PaymentFont#89]
I saw issue #11, but that's closed with implementation only of SEPA.

Direct Debit is one of the most prevalent forms of bill payment in the UK.  Also present in NZ.  There are online payment providers that provide DD (see separate issues).

DD font-awesome thread (going nowhere fast): https://github.com/FortAwesome/Font-Awesome/issues/1597

EPS logo available here: http://www.bacs.co.uk/Bacs/Businesses/Resources/Pages/DDIsAndLogos.aspx

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
