### ISSUE TITLE
Icon request: Klarna

### ISSUE THREAD

**Issue by peterbollen** [AlexanderPoellmann/PaymentFont#97]
Support for the Klarna payment method would be nice.

Their logo's can be found at https://developers.klarna.com/en/nl+php/kpm/logos

Thank you,
Peter

**Comment by dieterc** [comment]
I also need this one!

**Comment by eduardbrenninkmeijer** [comment]
Need this one as well, thx in advance!

**Comment by AlexanderPoellmann** [comment]
Added to v1.2.0 👍
